### PR TITLE
make attributes of portChanelPk struct public

### PR DESCRIPTION
**Pull request by dhruvja**
Making them public so that the `channel_id` and `port_id` can be accessed. 

Should we add getter method or making them public is fine?

### CODE REVIEW

**Comment by mina86** [comment]
Why do you need it? Dosn’t conversion to `TrieKey` cover all use cases?

**Comment by dhruvja** [comment]
> Why do you need it? Dosn’t conversion to `TrieKey` cover all use cases?

It does. I need it when i query the `channelEnds`.

**Comment by dhruvja** [comment]
Do you think we should have getter methods so that it converts `ChannelIdx` to `ChannelId`. Some like this
```rs
    pub fn channel_id(&self) -> ibc::ChannelId {
        ChannelId::new(self.channel_idx.into())
    }

    pub fn port_id(&self) -> ibc::PortId {
        self.port_id.clone()
    }
```

**Comment by mina86** [comment]
But if you’re querying channel ends what you need is `TrieKey::for_channel_end(&port_channel)`, no?

**Comment by dhruvja** [comment]
> But if you’re querying channel ends what you need is `TrieKey::for_channel_end(&port_channel)`, no?

In one of the methods, it queries all the `channel_id` and `port_Id` set, which requires me to return the keys of the struct below. But since the `port_id` and `channel_id` are private, i cannot access it.
```rs
pub channel_ends: BTreeMap<ids::PortChannelPK, Serialised<ibc::ChannelEnd>>,
```

**Comment by mina86** [comment]
OK, got it.  So what you need is to convert the PortChannelPK into `(ibc::PortId, ibc::ChannelId)`.

`channel_id` and `port_id` methods would be better here. `port_id` should return cloned id rather than a reference (this is because of https://github.com/ComposableFi/emulated-light-client/pull/116 which adds custom type for port id).

**Comment by dhruvja** [comment]
> OK, got it. So what you need is to convert the PortChannelPK into `(ibc::PortId, ibc::ChannelId)`.
> 
> `channel_id` and `port_id` methods would be better here. `port_id` should return cloned id rather than a reference (this is because of #116 which adds custom type for port id).

right right, got it. I will make the changes.

**Review by mina86 — APPROVED** [review]

**Pull request merged**
