### PR TITLE
docs(app): protocol for ibc app hosting and execution

### PR DESCRIPTION
**Pull request by dzmitry-lahoda**

### CODE REVIEW

**Review by blasrodri — APPROVED** [review]
LGTM

**Comment by dzmitry-lahoda** [comment]
@mina86 any question/comments about this?

**Comment by mina86** [comment]
I don’t have any specific questions or comments to the general idea outlined here.  The devil really is in the details of the implementation.

**Comment by dzmitry-lahoda** [comment]
@mina86 added more details and references

**Pull request merged**
